import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { COUNTRIES, priceData } from '../packages/catalogs/src/index';
import { canonical } from '../packages/contracts/src/index';
const hash = createHash('sha256')
  .update(canonical({ countries: COUNTRIES, prices: priceData }))
  .digest('hex');
if (process.argv.includes('--write'))
  writeFileSync(
    'packages/catalogs/src/fingerprint.ts',
    `// Generated by scripts/fingerprint-catalog.ts; catalog changes require a reviewed version change.\nexport const CATALOG_HASH = '${hash}';\n`,
  );
console.log(hash);
